#!/bin/bash

# LRT Database Population Script
# This script helps you populate your Render PostgreSQL database

echo "🚀 LRT Database Population Helper"
echo "==================================="
echo ""
echo "This script will help you populate your Render PostgreSQL database."
echo ""
echo "📋 What you need:"
echo "1. Your Render database connection details"
echo "2. Python 3 with psycopg2 installed"
echo ""
echo "🔍 To get your database credentials:"
echo "1. Go to your Render dashboard"
echo "2. Click on your 'lanesearch' database service"
echo "3. Copy the connection details"
echo ""
echo "📦 Install required Python package:"
echo "pip install psycopg2-binary"
echo ""
echo "🏃 Run the population script:"
echo "Method 1 - Set environment variables:"
echo "export DB_HOST='your-render-db-host'"
echo "export DB_PASSWORD='your-db-password'"
echo "python3 populate_database.py"
echo ""
echo "Method 2 - Edit the script directly:"
echo "1. Open populate_database.py"
echo "2. Update the DB_CONFIG dictionary with your credentials"
echo "3. Run: python3 populate_database.py"
echo ""
echo "✅ After successful population:"
echo "1. Go to Superset"
echo "2. Refresh database connection"
echo "3. Create datasets from tables: carriers, shippers, geo_data"
echo "4. Build your dashboard!"
echo ""
echo "🆘 Need help? Check the populate_database.py file for detailed instructions."